#!/usr/bin/env bash

# Parse options
add_newline=false
use_c_locale=true
join=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        -j|--join)
            join=true
            shift
            ;;
        -n|--newline)
            add_newline=true
            shift
            ;;
        -u|--unicode|--utf8)
            use_c_locale=false
            shift
            ;;
        *)
            break
            ;;
    esac
done

# Set locale (C locale for speed and reliability by default)
if $use_c_locale; then
    export LC_ALL=C
fi

if $join; then
    # Delete all whitespace (including newlines); optionally add trailing newline
    if $add_newline; then
        tr -d '[:space:]'
        echo
    else
        tr -d '[:space:]'
    fi
elif $add_newline; then
    # Trim and ensure trailing newline
    sed "s/^[[:space:]]*//;s/[[:space:]]*$//;/^$/d" | awk 'NR>1{print prev}{prev=$0}END{if(NR>0)print prev}'
else
    # Trim and remove trailing newline
    sed "s/^[[:space:]]*//;s/[[:space:]]*$//;/^$/d" | awk 'NR>1{print prev}{prev=$0}END{if(NR>0)printf "%s", prev}'
fi

# Alternative without removing blank lines (old behavior)
#sed "s/^[[:space:]]*//;s/[[:space:]]*$//"

# Alternative, seems almost as fast but maybe a little less portable
#pe "s/^\s+(.*?)\s*\n$/\1\n/"


